export const users=[
    {
        id:1,
        profilePicture:"Persons/th.jpg",
        username:"Gyashu Rahman",
    },
    {
        id:2,
        profilePicture:"Persons/user1.jpg",
        username:"Nauman ur Rahman",
    },
    {
        id:3,
        profilePicture:"Persons/user2.jpg",
        username:"Ayan Khan",
    },
    {
        id:4,
        profilePicture:"Persons/user3.jpg",
        username:"Rabia Bushra",
    },
    {
        id:5,
        profilePicture:"Persons/user4.jpg",
        username:"Ashraf Khan",
    },
    {
        id:6,
        profilePicture:"Persons/user5.jpg",
        username:"Sajid Alam",
    },
    {
        id:7,
        profilePicture:"Persons/user6.jpg",
        username:"Md Arman",
    }
]

export const posts =[
    {
        id:1,
        desc:"Be cold.. Be Fearless",
        photo:"posts/post1.jpg",
        date:"10 mins ago",
        userId:1,
        like:"43",
        comment:"7",
    },
    {
        id:2,
        desc:"Allah hu Akbar",
        photo:"posts/post12.jpg",
        date:"Before the big bang",
        userId:2,
        like:"100B+",
        comment:"100B+",
    },
    {
        id:3,
        desc:"Shine like sun to burn like sun",
        photo:"posts/post3.jpg",
        date:" 2 hr ago",
        userId:3,
        like:"34",
        comment:"12",
    },
    {
        id:4,
        desc:"hii how r u?",
        photo:"posts/post4.jpg",
        date:"21 aug 2022",
        userId:4,
        like:"875",
        comment:"23",
    },
    {
        id:5,
        desc:"what to write idk!!",
        photo:"posts/post5.jpg",
        date:"12 dec 2020",
        userId:5,
        like:"876",
        comment:"98",
    },
    {
        id:6,
        desc:"not creative",
        photo:"posts/post6.jpg",
        date:"55 min ago",
        userId:6,
        like:"321",
        comment:"11",
    },
    {
        id:7,
        desc:"hello beauty!!",
        photo:"posts/post7.jpg",
        date:"12 dec 2020",
        userId:7,
        like:"1",
        comment:"2",
    },
    {
        id:8,
        desc:"not creative",
        photo:"posts/post8.jpg",
        date:"55 min ago",
        userId:6,
        like:"321",
        comment:"11",
    },
    {
        id:9,
        desc:"Shine like sun to burn like sun",
        photo:"posts/post1.jpg",
        date:" 2 hr ago",
        userId:3,
        like:"34",
        comment:"12",
    },
    {
        id:10,
        desc:"Allah hu Akbar",
        photo:"posts/post2.jpg",
        date:"Before the big bang",
        userId:2,
        like:"100B+",
        comment:"100B+",
    },
    {
        id:11,
        desc:"Be cold.. Be Fearless",
        photo:"posts/post11.jpg",
        date:"10 mins ago",
        userId:1,
        like:"43",
        comment:"7",
    },
    {
        id:12,
        desc:"Allah hu Akbar",
        photo:"posts/post12.jpg",
        date:"Before the big bang",
        userId:1,
        like:"100B+",
        comment:"100B+",
    },
    {
        id:13,
        desc:"Allah hu Akbar",
        photo:"posts/post13.jpg",
        date:"Before the big bang",
        userId:2,
        like:"100B+",
        comment:"100B+",
    },
    {
        id:14,
        desc:"not creative",
        photo:"posts/post14.jpg",
        date:"55 min ago",
        userId:6,
        like:"321",
        comment:"11",
    },
    {
        id:15,
        desc:"Shine like sun to burn like sun",
        photo:"posts/post15.jpg",
        date:" 2 hr ago",
        userId:3,
        like:"34",
        comment:"12",
    },
    {
        id:16,
        desc:"what to write idk!!",
        photo:"posts/post16.jpg",
        date:"12 dec 2020",
        userId:5,
        like:"876",
        comment:"98",
    }
]
